# TCL File Generated by Component Editor 15.0
# Thu May 14 04:23:07 JST 2015
# DO NOT MODIFY


# 
# rand_xorshift128 "rand_xorshift128" v1.0
#  2015.05.14.04:23:07
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module rand_xorshift128
# 
set_module_property DESCRIPTION ""
set_module_property NAME rand_xorshift128
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rand_xorshift128
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL custom_instr_rand
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file custom_instr_rand.v VERILOG PATH custom_instr_rand.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point cis
# 
add_interface cis nios_custom_instruction end
set_interface_property cis clockCycle 0
set_interface_property cis operands 0
set_interface_property cis ENABLED true
set_interface_property cis EXPORT_OF ""
set_interface_property cis PORT_NAME_MAP ""
set_interface_property cis CMSIS_SVD_VARIABLES ""
set_interface_property cis SVD_ADDRESS_GROUP ""

add_interface_port cis clk clk Input 1
add_interface_port cis clk_en clk_en Input 1
add_interface_port cis reset reset Input 1
add_interface_port cis result result Output 32

